spring:
  application:
    name: tecnos-server
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/tecnos_db?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: Decembrie2001

  jwt:
    secretKey: asdasdasdasdasd123344asdasdasdasdasasd12321332sadas
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 7

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB


springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

#aws:
#  accessKey: 005df870e6d8e2a0000000003
#  secretKey: K005chWsD61WVtb2Sj4SRspzaKKO+wc
#  region: us-east-005


logging:
  level:
    org.springframework.cloud.sleuth: DEBUG
    org.springframework.web.client.RestTemplat: DEBUG
metrics:
  distribution:
    percentiles-histogram:
      http:
        server:
          request: true
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logs:
  destination: localhost:3100